# SwiftLint configuration for DidYouGet

# Paths to include/exclude
included:
  - DidYouGet/
  - Tests/

excluded:
  - .build/
  - release/
  - _external/

# Rules
disabled_rules:
  - trailing_whitespace # Handled by swift-format
  - line_length # Will be handled by swift-format

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - number_separator
  - object_literal
  - overridden_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 120
  error: 200

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print"
    severity: warning