name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git describe
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Run tests
      run: |
        chmod +x build.sh
        ./build.sh debug --test --clean
    
    - name: Build release
      run: |
        ./build.sh release
    
    - name: Create release archive
      run: |
        cd release
        tar -czf DidYouGet-${{ steps.get_version.outputs.version }}-macos.tar.gz DidYouGet version.txt
    
    - name: Generate release notes
      id: release_notes
      run: |
        # Get the previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        # Generate changelog
        if [ -n "$PREVIOUS_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s" HEAD)
        fi
        
        # Create release notes
        cat > release_notes.md << EOF
        # Release ${{ steps.get_version.outputs.version }}
        
        ## Changes
        $CHANGELOG
        
        ## Installation
        1. Download the \`DidYouGet-${{ steps.get_version.outputs.version }}-macos.tar.gz\` file
        2. Extract it: \`tar -xzf DidYouGet-${{ steps.get_version.outputs.version }}-macos.tar.gz\`
        3. Run the executable: \`./DidYouGet\`
        
        ## Requirements
        - macOS 13.0 or later
        - Screen recording permissions may be required
        
        ## Full Changelog
        **Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...${{ steps.get_version.outputs.tag }}
        EOF
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: Release ${{ steps.get_version.outputs.version }}
        body_path: release_notes.md
        files: |
          release/DidYouGet-${{ steps.get_version.outputs.version }}-macos.tar.gz
          release/version.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: |
          release/DidYouGet-${{ steps.get_version.outputs.version }}-macos.tar.gz
          release/version.txt
        retention-days: 90